### ISSUE TITLE
Website on Hackday

### ISSUE THREAD

**Issue by nikhilaravi** [node-girls/hackday#7]
@NataliaLKB  I would like to help with the website on the hackday! :)

**Comment by iteles** [comment]
I'd love to be your CSS gal for the website too ;)

**Comment by NataliaLKB** [comment]
Thats great! How fun!

**Comment by NataliaLKB** [comment]
@nikhilaravi @iteles and I are all working on the website today :blush:

**Comment by NataliaLKB** [comment]
Website design ideas here: https://github.com/node-girls/start-here/issues/7

**Comment by NataliaLKB** [comment]
Closing in favour of https://github.com/node-girls/hackday/issues/9
